.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH patscc 1 "October 8, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
patscc \- ATS2 compiler frontend
.SH SYNOPSIS
.B patscc
.RI [ options ] " files" ...
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.B patscc
is a frontend to the Postiats compiler
.B patsopt
for the ATS2 language.
.SH OPTIONS
.B patscc
has a command-line option syntax in the style of
.B gcc
and accepts all the same options, many of them being passed directly to the
.B gcc
backend.  Here are summarized the non-\fBgcc\fP options.
.TP
.B \-atsccomp <command>
Specify the name of the C compiler on the command line. Otherwise, use environment variable
.B ATSCCOMP
or the default. See further details on environment variables.
.TP
.B \-cleanaft
Clean up incidental generated C files after compilation finishes.
.TP
.B \-\-compile, \-ccats
Only compile the given ATS source files into C files.
.TP
.B \-DATS <name>[=<value>], \-DDATS <name>[=<value>]
Define a name/value macro toplevel value in ATS.
.B \-DDATS
also passes this option to the C compiler.
.TP
.B \-IATS <path>, \-IIATS <path>
Add a path to search for ATS files when doing static and dynamic loads.
.B \-IIATS
also passes this path to the C compiler.
.TP
.B \-fsats <file>, \-fdats <file>
These indicate that the following file is a SATS or a DATS file. Unnecessary if standard filename extensions
.B .sats
or
.B .dats
are used.
.TP
.B \-\-gline
Place line pragma information based on ATS source in the generated C code.
.TP
.B \-\-typecheck, \-tcats
Typecheck the given ATS source files, but go no further.
.TP
.B \-\-version, \-vats
Show ATS2/Postiats version and gcc version.
.SH ENVIRONMENT VARIABLES
.TP
.B PATSCCOMP, ATSCCOMP
Use the value of this environment variable as the command name of the C compiler. The default is
.B gcc -D_XOPEN_SOURCE -I${ATSHOME} -I${ATSHOME}/ccomp/runtime -L${ATSHOME}/ccomp/atslib/lib
.TP
.B PATSHOME, ATSHOME
Use the value of this environment variable as the path to the ATS library installation. The default is distribution-specific.
.TP
.B PATSOPT, ATSOPT
Use the value of this environment variable as the command name of the ATS compiler. The default is
.B patsopt.
.SH EXAMPLES
.PP
.B patscc -o test -O3 test.dats
.PP
Compile test.dats to an executable named test.  Tell
.B gcc
to use the third level of optimization.
.PP
.B patscc -tcats test.dats
.PP
Typecheck test.dats only.
.PP
.B patscc -ccats test.dats
.PP
Compile to C file test_dats.c only.
.PP
.B patscc -o test.o -c test.dats -cleanaft
.PP
Compile test.dats to an object file named test.o, and delete intermediate C file.
.SH SEE ALSO
.BR patsopt (1),
.br
These programs are documented fully by
.B The ATS2/Postiats user's manual
available via the web at http://www.ats-lang.org/
.SH AUTHOR
patscc was written by Hongwei Xi.
.PP
This manual page was written by Matthew Danish <mrd@debian.org>,
for the Debian project (and may be used by others).
